apiVersion: batch/v1
kind: Job
metadata:
  name: check-sa-annotation-job
  annotations: 
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: check-sa-annotation-container
        image: docker-dev-artifactory.workday.com/scylla-silver/kubectl:1.19.2.0
        command: ["/bin/sh", "-c", "kubectl get sa -n aws-lb-controller aws-load-balancer-controller -o=jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}' | grep -q . && exit 0 || exit 1 "]
      restartPolicy: OnFailure
      initialDelaySeconds: 10
  backoffLimit: 3
