apiVersion: batch/v1
kind: Job
metadata:
  name: check-sa-annotation-job
  annotations: 
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: check-sa-annotation-container
        image: docker-dev-artifactory.workday.com/scylla-silver/kubectl:1.19.2.0
        command: ["/bin/sh", "-c", "if kubectl get serviceaccount testserviceacc -n default -o=jsonpath='{.metadata.annotations.tstana}' | grep -q available; then exit 0; else exit 1; fi"]
      restartPolicy: OnFailure
  backoffLimit: 3
